### ISSUE TITLE
Generate isbn for requested licence number

### ISSUE THREAD

**Issue by st249** [st249/BH#59]
Create generation function of isbn for requested license number...
1. Check existence of publisher 
2. Check isbn availability
3. Generate isbn and return proper status code to requester

**Comment by st249** [comment]
Should add flowchart and sequence diagram for this purpose

**Comment by st249** [comment]
1dd6c523b57836539c570adb6f6f224f362c2075

Added flow chart

**Comment by melody75ru** [comment]
Check extistance of publisher is ok and just need to test.
About check isbn availability we  should talk more I'm not justified .

**Comment by st249** [comment]
8eb1c07213828c33b21d6d887c84ced681d35ad7

Generation is Done... 
Just need error code and registration which need the ministry web service

**Comment by st249** [comment]
Flag Pulisher For New Element is Done.

**Comment by st249** [comment]
#65 
Merging To master

**Comment by st249** [comment]
Checking existance of publisher is done
just need to check #74

**Comment by st249** [comment]
Temp Data is Done just need to create panel for Isbn
